# Lefthook configuration for git hooks
# https://github.com/evilmartians/lefthook

pre-commit:
  parallel: true
  commands:
    ruff-check:
      glob: "*.py"
      run: uv run ruff check --fix {staged_files}
      stage_fixed: true
    ruff-format:
      glob: "*.py"
      run: uv run ruff format {staged_files}
      stage_fixed: true

commit-msg:
  commands:
    gitlint:
      run: uv run gitlint --staged --msg-filename {1}
